name: SmartEye

networks:
  kafka-net:
    driver: bridge

volumes:
  kafka_data:

services:

  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - kafka_data:/bitnami/kafka

  videobuffer0:
    build:
      context: ./ESP32CAM-VideoBuffer
      dockerfile: ../ESP32CAM-VideoBuffer.Dockerfile
    networks:
      - kafka-net
    depends_on:
      - kafka